### ISSUE TITLE
Prevent navigation below the terrain

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/worldwindjs#10]
Enhance the default navigation behavior to prevent the camera from going below the terrain.

**Comment by EMaksymenko** [comment]
I know how to do it.
1) Correct near clip distance calculation in WorldWindow.prototype.computeViewingTransform taking terrain elevation and vertical exaggeration in account, as I already done in Android.
2) Limit navigator to the terrain altitude + threshold to avoid setting camera below surface.

But it would be better to do with general camera processing refactoring, after we switch lookAtPostion navigation to eyePosition navigation approach.

**Comment by EMaksymenko** [comment]
Fixed in PR #39
